### ISSUE TITLE
Corrupted text on iPhone 6

### ISSUE THREAD

**Issue by bcamper** [mapzen/ios#286] opened 2017-04-24 15:22 UTC
### Description
I'm seeing a couple variants of corrupted or missing text.

Random characters / corrupt label:
![img_5417](https://cloud.githubusercontent.com/assets/16733/25344394/fabbb6d8-28df-11e7-8b31-761eba00a960.PNG)

Missing labels:
![img_5420](https://cloud.githubusercontent.com/assets/16733/25344403/fe899fd2-28df-11e7-86c2-a6079bb37d87.PNG)

### Steps to Reproduce
- Opened app, zoomed to Central Park, noticed corrupt labels
- Zoomed out, noticed missing text on shields
- Cannot reproduce every time I use the app, but reproduced missing shield text on second or third attempt (have only seen that specific type of corrupt label text in first screenshot the one time).

### Mapzen SDK & iOS Version
SDK 0.4.0
iOS 10.2.1
iPhone 6

**Comment by meetar** [comment] 2017-04-24 15:34
FTR I can't reproduce on iPhone 5s with iOS 10.3.1.

**Comment by msmollin** [comment] 2017-04-24 16:16
Been able to reproduce this twice, but only once per device. Subsequent runs and rebuilds and app deletions / reinstalls have been fine.

iPad Mini 1 running iOS 9.3.5:
![screen shot 2017-04-24 at 12 08 41 pm](https://cloud.githubusercontent.com/assets/1163880/25347121/d66610aa-28e7-11e7-9792-b398438b7744.png)

iPad Mini 2 Running iOS 10.2.1:
![screen shot 2017-04-24 at 12 08 41 pm](https://cloud.githubusercontent.com/assets/1163880/25347131/dcc68416-28e7-11e7-9e5a-fde2014d92c2.png)

**Comment by msmollin** [comment] 2017-04-24 16:17
Have not seen the font issue that @bcamper originally mentioned on any device.

**Comment by msmollin** [comment] 2017-04-26 15:29
Just to follow up here:
@tallytalwar and @hjanetzek discovered an issue inside the alfons project that Tangram-es utilizes to load in and store font-faces. This issue is being fixed upstream in alfons which then will result in needing updating inside Tangram-es. 

Additionally the Tangram-es iOS framework will introduce changes to limit the number of system font families it attempts to load when attempting to render certain glyphs.

In the meantime until those changes are implemented, deployed, and tested, I've branched the 5 house styles we're shipping in the 1.0 release and removed the bundled fonts from those styles. When fonts are bundled, Tangram-es attempts to pre-load them for rendering performance improvements, which has the side affect of consuming available memory for system fonts that need to be loaded. 

Removing these bundled fonts forces Tangram-es to utilize system fonts on-demand for *all* glyphs at render timer. By only loading the fonts needed for the glyphs on currently on-screen that need rendering, this reduces the memory constraints on alfons. This does have performance implications on older devices.

**Comment by msmollin** [comment] 2017-04-26 21:10
Here's screen shots of the very similar views but using just the system fonts for display. 

![screen shot 2017-04-26 at 3 00 14 pm](https://cloud.githubusercontent.com/assets/1163880/25457071/f9f0c134-2aa2-11e7-8d8f-56a3d251ed50.png)

![screen shot 2017-04-26 at 5 07 28 pm](https://cloud.githubusercontent.com/assets/1163880/25457068/f698b8de-2aa2-11e7-8fa3-cd9c062d8190.png)

**Comment by msmollin** [comment] 2017-04-27 18:06
Moving this back to the backlog so we can track it with tangram-es 0.7 launch

**Comment by msmollin** [comment] 2017-05-03 18:59
This got fixed as part of 0.5.2 / 0.6.2 so we'll close this.

**Closed** 2017-05-03 18:59 UTC
