### ISSUE TITLE
Rename TangramVC to TangramViewController

### ISSUE THREAD

**Issue by msmollin** [mapzen/ios#172] opened 2017-02-22 05:00 UTC
Per some outside feedback and previous feedback from @karimnaaji we should refactor TangramVC to be more explicitly declared.

**Comment by karimnaaji** [comment] 2017-02-22 15:13
Duplicate of https://github.com/mapzen/ios/issues/74?

**Comment by msmollin** [comment] 2017-02-22 15:18
Arguably, although that one is a little less specific. We could combine the two.

**Closed** 2017-03-28 20:59 UTC
Labels: in progress
